### ISSUE TITLE
zaboy\res\Middleware\MiddlewareMemoryStore

### ISSUE THREAD

**Issue by victorynox** [avz-cmf/zaboy-res#4]
В конструкторе нужно добавить вызов родительского конструктора, что бы не переопределять поведение метода.
`public function __construct(Memory $dataStore =null)`
`{`
`if ($dataStore !== null) {`
`parent::__construct($dataStore); `
`}else{`
`parent::__construct(new Memory()); `
`}`
`}`

**Comment by avz-cmf** [comment]
if (empty($dataStore)) {
            $dataStore = new Memory();
        }
        parent::__construct($dataStore);
