### ISSUE TITLE
 zaboy-res/src/DataStore/HttpClient.php  

### ISSUE THREAD

**Issue by victorynox** [avz-cmf/zaboy-res#8]
в методе __construct($url, $options = null, ConditionBuilderAbstract $conditionBuilder = null)
url будет null, если $options не массив 

> код содержащий ошибку

`if (is_array($options)) {`
           ` if (isset($options['login']) && isset($options['password'])) {`
             `   $this->login = $options['login'];`
           `     $this->password = $options['password'];`
          `  }`
          **`  $this->url = rtrim(trim($url),'/');`**
          `  $supportedKeys = [`
          `      'maxredirects',`
           `     'useragent',`
          `      'timeout',`
         `   ];`
         `   $this->options = array_intersect_key($options, array_flip($supportedKeys));`
     `   }`

**Comment by avz-cmf** [comment]
parent::__construct($options);
        $this->url = rtrim(trim($url),'/');        
        if (is_array($options)) {
            if (isset($options['login']) && isset($options['password'])) {
                $this->login = $options['login'];
                $this->password = $options['password'];
            }
            $supportedKeys = [
                'maxredirects',
                'useragent',
                'timeout',
            ];
            $this->options = array_intersect_key($options, array_flip($supportedKeys));
        }

Переделал
