### ISSUE TITLE
 zaboy-res/src/DataStores/ConditionBuilderAbstract.php

### ISSUE THREAD

**Issue by victorynox** [avz-cmf/zaboy-res#9]
В методе `public function  makeScalarOperator(AbstractScalarOperatorNode  $node)`
не проверяется значение (value), в случае если это дата будет выброшен exception
`$this->prepareFildValue($node->getValue()) `

> можно исправить так
`$strQuery =`
 `           $this->literals['ScalarOperator'][$nodeName]['before']`
  `          . $this->prepareFildName($node->getField())`
   `         . $this->literals['ScalarOperator'][$nodeName]['between'];`
    `    if ($node->getValue() instanceof \DateTime) {`
     `       $strQuery .=`
      `          $this->prepareFildValue($node->getValue()->format("Y-m-d"))`
       `         . $this->literals['ScalarOperator'][$nodeName]['after'];`
       ` } else {`
        `    $strQuery .=`
         `       $this->prepareFildValue($node->getValue())`
          `      . $this->literals['ScalarOperator'][$nodeName]['after'];`
        `}`

**Comment by avz-cmf** [comment]
$nodeName = $node->getNodeName();
        $value = $node->getValue() instanceof \DateTime ? $node->getValue()->format("Y-m-d") : $node->getValue();       
        $strQuery =
            $this->literals['ScalarOperator'][$nodeName]['before']
            . $this->prepareFildName($node->getField())
            . $this->literals['ScalarOperator'][$nodeName]['between']
            . $this->prepareFildValue($value) 
            . $this->literals['ScalarOperator'][$nodeName]['after'];
                
        return $strQuery;

Так лучше?
